
__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdemrv2_mamba2_e_r50vd.yml',
]


output_dir: ./output_rtdemrv2/mamba2_e_r18vd_256_2_16_rms_fused_residualfp32
checkpoint_step: 5

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True

Mamba2_HybridEncoder:
  depth: 2
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5
  residual_in_fp32: True


RTDETRTransformer:
  feat_channels: [256, 256, 256]
  hidden_dim: 256
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100



optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

